### ISSUE TITLE
Projects should have required fields

### ISSUE THREAD

**Issue by darwinfroese** [darwinfroese/hacksite#30]
*Please look at the contributing document or wiki page prior to contributing!*

## Summary

Name should be required.

## Notes

Can make use of VeeValidate package that is used for validating on account creation.

**Comment by PriyankaGitHub7** [comment]
@darwinfroese I am interested in working on this. Can I install vee-validate package? I don't see it already installed.

**Comment by darwinfroese** [comment]
Awesome. Yes, I am thinking something similar.

If you check out PR #28 you can see what VeeValidate looks like by default. The package was installed their but you can feel free to install it as well and then we'll just deal with the merge conflicts later :)

**Comment by PriyankaGitHub7** [comment]
@darwinfroese I have added a new component to represent all the required text fields as shown here
https://github.com/darwinfroese/hacksite/compare/master...PriyankaGitHub7:add-required-fields?expand=1#diff-38bf11f68296657cdc61e0c18c70491e, so that it can be reused. Could you please check this and let me know if this is fine.

**Comment by darwinfroese** [comment]
Sounds good! Can you submit a PR for the project and I'll review the code in there

**Comment by darwinfroese** [comment]
This work will be covered in the rebranding.
